name: test angular deploy to s3

on:
  push:

jobs:
  s3ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1' # リージョンを指定
         # role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}' # 作成した IAM ロールの ARN
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Deploy to S3
        run: |
          ls ./dist/angular-github-actions/browser/
          aws s3 sync ./dist/angular-github-actions/browser/ s3://toma-github-actions-test/ --delete
        